---
- name: Installing aptitude
  apt: pkg=aptitude

- name: Upgrade cache and system (safe upgrade)
  apt: upgrade=safe update_cache=yes

- name: Install git
  apt: pkg=git,python-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: Installing build-tools
  apt: pkg=build-essential,autoconf,libtool,pkg-config,libpq-dev,python-mysqldb,imagemagick,unzip,curl,npm

- name: Add {{ username }} to www-data group
  become: true
  command: usermod -a -G www-data vagrant